image: ubuntu:18.04

before_script:
  - apt-get update

  - apt-get install -y curl
  # https://askubuntu.com/a/1013396
  - DEBIAN_FRONTEND=noninteractive apt-get install -y nuget mono-complete mono-xbuild fsharp

stages:
  - build
  - test

build:
  stage: build
  script:
    - time (./configure.sh && make && make install)
    # so that we log the version of nuget for when it works
    - make nuget

test:
  stage: test
  script:
    - time (apt-get install -y nunit-console &&
            ./configure.sh &&
            make &&
            make check)
