before_script:
  - apt-get update
  # needed to download NuGet
  - apt-get install -y curl

stages:
  - build
  - test

newmono_build:
  image: ubuntu:18.04
  stage: build
  script:
    - ./scripts/install_mono_from_microsoft_deb_packages.sh

    # NOTE: this is needed as a workaround to this bug: https://github.com/mono/mono/issues/10570
    - ./scripts/install_dotnet_sdk_from_microsoft_deb_packages.sh

    # so that it builds the GTK frontend
    - apt install -y libgtk2.0-cil-dev

    - time (./configure.sh && make && make install)
    # so that we log the version of nuget for when it works
    - make nuget

