image: ubuntu:18.04

before_script:
  - apt-get update
  # needed to download NuGet
  - apt-get install -y curl

stages:
  - build
  - test

stockmono_build:
  stage: build
  script:
    # https://askubuntu.com/a/1013396
    - DEBIAN_FRONTEND=noninteractive apt-get install -y nuget mono-complete mono-xbuild fsharp
    - mono --version

    - time (./configure.sh && make && make install)
    # so that we log the version of nuget for when it works
    - make nuget

stockmono_test:
  stage: test
  script:
    # https://askubuntu.com/a/1013396
    - DEBIAN_FRONTEND=noninteractive apt-get install -y nuget mono-complete mono-xbuild fsharp

    - time (apt-get install -y nunit-console &&
            ./configure.sh &&
            make &&
            make check)

newmono_build:
  stage: build
  artifacts:
    paths:
      - bin/*.zip
    expire_in: 1 week
  script:
    - ./scripts/install_mono_from_microsoft_deb_packages.sh

    # NOTE: this is needed as a workaround to this bug: https://github.com/mono/mono/issues/10570
    # TODO: check for .NET SDK in the configure.fsx file as well
    # below is to install .NET SDK, taken from https://www.microsoft.com/net/download/linux-package-manager/ubuntu18-04/sdk-current
    - apt install -y wget
    - wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
    - dpkg -i packages-microsoft-prod.deb
    - apt install -y apt-transport-https
    - apt update
    - apt install -y dotnet-sdk-2.1

    # so that it builds the GTK frontend
    - apt install -y libgtk2.0-cil-dev

    - time (./configure.sh && make && make install)
    # so that we log the version of nuget for when it works
    - make nuget

    - apt-get install -y zip
    - make zip

newmono_test:
  stage: test
  script:
    - ./scripts/install_mono_from_microsoft_deb_packages.sh

    - apt install -y nunit-console

    - time (./configure.sh && make && make check)
