name: geewallet
base: core20 # the base snap is the execution environment for this snap
version: '0.4.228.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: minimalistic cryptocurrency brainwallet # 79 char long summary
description: |
  Non-custodial, minimalistic and pragmatist opensource crossplatform
  lightweight brainwallet for people that want to hold the most important
  cryptocurrencies in the same application with ease & peace of mind.
license: MIT
icon: logo.png

grade: stable
confinement: strict

layout:
  /usr/share/.mono:
    symlink: $SNAP/etc/mono/certstore
  /usr/lib/cli:
    symlink: $SNAP/usr/lib/cli

apps:
  geewallet:
    command: bin/desktop-launch $SNAP/bin/geewallet-gtk
    plugs:
      - network
      - desktop
      - desktop-legacy
      - wayland
      - unity7

parts:
  geewallet:
    plugin: dump
    source: ./staging
    stage-packages:
      - mono-devel
      - libgtk2.0-cil

  certs:
    plugin: dump
    source: /etc/mono
    organize:
      certstore: etc/mono/certstore

  gtk2:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk2"]
    build-packages:
      - libgtk2.0-dev
    stage-packages:
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk2.0-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk2.0-bin
      - unity-gtk2-module
      - libappindicator1
      - locales-all
      - ibus-gtk
      - libibus-1.0-5
