name: macOS

on: [push]

jobs:
  macOS_build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: ./configure.sh && make release

  macOS_tests:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: ./configure.sh && make && make check
