name: ubuntu

on: [push]

jobs:
  ubuntu-snap-build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Generate snap package
      run: |
        ./scripts/install_snapcraft.sh
        sudo ./scripts/snap_build.sh

    - name: Upload snap package as artifact
      uses: actions/upload-artifact@v1
      with:
        name: snap
        path: gwallet_0.3.1.1_amd64.snap

